### ISSUE TITLE
Need CPU objects

### ISSUE THREAD

**Issue by bdha** [joyent/conch-reporter-smartos#5]
`hwgrok` does not give us CPU info. We'll need to collect it some other way.

The very minimum we need is:

```
  "processor": {
    "count": 2,
    "type": "Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz"
  },
```

Under Linux, we push up about 1000 lines of CPU flags. I don't think that's critical information, but things like:

```
      "microcode": "0x2000043",
      "model_family": "6",
      "model_id": "85",
      "model_name": "Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz",
      "model_stepping": "4",
      "socket_id": "1"
```

from each CPU would be helpful.

**Comment by bdha** [comment]
See `smbios -t 4`.

**Comment by bdha** [comment]
Actually, getting this from `sysinfo` is probably easier.

**Comment by rejohnst** [comment]
topo has some of that stuff (lilke model/stepping/family no's) - I just didn't plumb it up through hwgrok, because I wasn't sure if it was interesting to people.  topo doesn't yet have the model string - but I do plan to address that - see OS-7150

**Comment by bdha** [comment]
```
# cat /tmp/conch-report.json | json conch.processor
{
  "count": 2,
  "type": "Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz"
}
```
